google_analytics:

title: muldev.com
email: simon@muldev.com
description: Developers for the modern web
author: Simon Assouline
url: https://muldev.com
github_username: muldev
twitter_username: muldev2
future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude: [
    package.json,
    package-lock.json,
    postcss.config.js,
    tailwind.config.js,
    readme.md,
    assets/css/tailwind.config.css,
    assets/css/tailwind.css,
    LICENSE
]

# Using Jekyll Compress:
# http://jch.penibelst.de/
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []